### ISSUE TITLE
waitng for you help brother kindly help me solve the task

### ISSUE THREAD

**Issue by KetanRode4** [rajmadhu0406/Dog_Breeds_Classification#1]

**Comment by rajmadhu0406** [comment]
This is your assignment, the company wants to evaluate your skills. I won't help you solve everything but I can guide you. Here are some points you can go after:

As far I understood the assignment, you can do the following:

1)scrape LinkedIn for companies having the keyword AI (or similar) and analyzing the location of these companies. Then you can plot a graph showing how many AI companies are there in a country.

2)Then you can scrape research journals and analyze which country has most papers in the AI field.

3)You can also select a AI product and check their user distribution across different countries.

**Comment by KetanRode4** [comment]
________________________________

**Comment by KetanRode4** [comment]
How to do scraping of AI companies on linkedin
________________________________

**Comment by rajmadhu0406** [comment]
This is your assignment, the company wants to evaluate your skills. I won't
help you solve everything but I can guide you. Here are some points you can
go after:

As far I understood the assignment, you can do the following:

1)scrape LinkedIn for companies having the keyword AI (or similar) and
analyzing the location of these companies. Then you can plot a graph
showing how many AI companies are there in a country.

2)Then you can scrape research journals and analyze which country has most
papers in the AI field.

3)You can also select a AI product and check their user distribution across
different countries.
